name: Check-in Tracker

on:
  issues:
    types: [opened]

jobs:
  update-checkin:
    if: startsWith(github.event.issue.title, 'check-in')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract check-in title to env
        run: |
          echo "ISSUE_TITLE=${{ github.event.issue.title }}" >> $GITHUB_ENV

      - name: Parse date from issue title and update data.json
        run: |
          DATE=$(echo "$ISSUE_TITLE" | sed 's/check-in //')
          FILE=data.json
          if [ ! -f "$FILE" ]; then echo '{"dates":[]}' > "$FILE"; fi
          node -e '
            const fs = require("fs");
            const file = "data.json";
            const date = process.env.DATE;
            const data = JSON.parse(fs.readFileSync(file));
            if (!data.dates.includes(date)) {
              data.dates.push(date);
              data.dates = data.dates.filter(Boolean).sort();
              fs.writeFileSync(file, JSON.stringify(data, null, 2));
            }
          '
        env:
          DATE: ${{ env.ISSUE_TITLE }}

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data.json
          git commit -m "Add check-in for $DATE" || echo "No changes to commit"
          git push